name: Mirobot
markdown: redcarpet
pygments: true
paginate: 4
paginate_path: "blog/page:num"
permalink: /blog/:year/:month/:day/:title/
exclude:
 - Gemfile
 - Gemfile.lock
 - s3_website.yml
 - README.md
 - vendor